<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dmz_app_description'] = 'Приложение DMZ  предоставляет инструменты брандмауэра для систем в демилитаризованной зоне. Изоляция высокого риска внешних услуг, таких как веб-, электронной почте и системе VoIP может улучшить безопасность вашей сети.';
$lang['dmz_app_name'] = 'DMZ Фаервол';
$lang['dmz_incoming_connection'] = 'Входящее соединение DMZ';
$lang['dmz_incoming_connections'] = 'Входящие соединения DMZ';
$lang['dmz_network_not_configured'] = 'Сетевой интерфейс с определенной ролью DMZ не может быть найден.';
$lang['dmz_pinhole_connection'] = 'DMZ Pinhole (DMZ к LAN) соединение';
$lang['dmz_pinhole_connections'] = 'DMZ Pinhole (DMZ к LAN) соединение';
