<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dmz_app_description'] = 'DMZ-appen ger dig brandväggsverktyg för systm i den demilitariserade zonen.   Genom att isolera externa tjänster som  webb, e-post och VOIP-system så kan detta öka säkerheten för ditt nätverk.';
$lang['dmz_app_name'] = 'DMZ-brandväggen';
$lang['dmz_incoming_connection'] = 'DMZ inkommande anslutning';
$lang['dmz_incoming_connections'] = 'DMZ inkommande anslutningar';
$lang['dmz_network_not_configured'] = 'Ett nätverkskort som har en utpekad roll i DMZ kunde inte hittas.';
$lang['dmz_pinhole_connection'] = 'DMZ nålsögats (DMZ till LAN) anslutning';
$lang['dmz_pinhole_connections'] = 'DMZ nålsögats (DMZ till LAN) anslutningar';
