<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['dmz_app_description'] = 'Aplikacja DMZ dostarcza usługi firewalla dla systemów w strefie zdemilitaryzowanej .  Izolując zewnętrzne usługi wysokiego ryzyka takie jak www, e-mail czy systemy VoIP można zwiększyć bezpieczeństwo Twojej sieci.';
$lang['dmz_app_name'] = 'Firewall DMZ';
$lang['dmz_incoming_connection'] = 'Połączenie przychodzące DMZ';
$lang['dmz_incoming_connections'] = 'Połączenia przychodzące DMZ';
$lang['dmz_network_not_configured'] = 'Interfejs sieciowy z przydzieloną rolą DMZ nie został znaleziony.';
$lang['dmz_pinhole_connection'] = 'Połączenie szczególne DMZ (DMZ do LAN)';
$lang['dmz_pinhole_connections'] = 'Połączenia szczególne DMZ (DMZ do LAN)';
